// Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Specialized knowledge

This deployment guide requires a moderate level of familiarity with AWS services. If you’re new to AWS, see the https://aws.amazon.com/getting-started/[Getting Started Resource Center] and https://aws.amazon.com/training/[AWS Training and Certification]. These sites provide materials for learning how to design, deploy, and operate your infrastructure and applications on the AWS Cloud.

This Partner Solution assumes familiarity with https://aws.amazon.com/eks/[Amazon EKS], https://aws.amazon.com/cloudformation/[AWS CloudFormation], and https://kubernetes.io/[Kubernetes].

==== AWS account

If you don’t already have an AWS account, create one at https://aws.amazon.com by following the on-screen instructions. Part of the sign-up process involves receiving a phone call and entering a PIN using your phone’s keypad.

Your AWS account is automatically signed up for all AWS services. You are charged only for the services you use.

==== IAM permissions

Before launching the Partner Solution, you must log in to the AWS Management Console with https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html[IAM permissions] for the resources and actions the templates deploy.

The _AdministratorAccess_ managed policy within IAM provides sufficient permissions, although your organization may choose to use a custom policy with more restrictions.

=== Prepare existing EKS cluster

NOTE: This step is only required if you launch this Partner Solution into an existing Amazon EKS cluster that was not created using the Amazon EKS on the AWS Cloud deployment. If you want to create a new EKS cluster with your deployment, this step can be skipped.

. Sign in to your AWS account, and launch the cluster preparation template.
. The template launches in the US East (Ohio) Region by default. To change the Region, choose another Region from list in the upper-right corner of the navigation bar.
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Enter the name of the Amazon EKS cluster you want to deploy to as well as the subnet IDs and security group ID associated with the cluster. These can be obtained from the EKS cluster console.
. On the *Options* page, specify the key-value pairs for resources in your stack, and set advanced options. When you’re done, choose *Next*.
. On the *Review* page, review and confirm your template settings. Under *Capabilities*, select the two check boxes to acknowledge that the template creates IAM resources and might require the ability to automatically expand macros.
. Choose *Create stack* to deploy the stack.
. Monitor the stack’s status until it is *CREATE_COMPLETE*.
. From the *Outputs* section of the stack, note the KubernetesRoleArn and HelmRoleArn roles.
. Add the roles to the aws-auth config map in your cluster, specifying system:masters for the groups. This allows the Partner Solution to manage your cluster via AWS CloudFormation. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html[Managing users or IAM roles for your cluster].

=== ACM certificate

The {partner-company-name} {partner-product-short-name} UI service's load balancer requires a valid
https://docs.aws.amazon.com/acm/[AWS Certificate Manager(ACM)]https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html[certificate].

Option 1: Let the Partner Solution create one.

* Provide both a Route 53 Hosted Zone ID and domain name for the {partner-product-short-name} load balancer.

Option 2: Bring your own.

* Provide your own ACM certificate using its
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awscertificatemanager.html#awscertificatemanager-resources-for-iam-policies[Amazon Resource Name(ARN)].

NOTE: The ACM certificate must reside in the same AWS Region in which you deploy this Partner Solution.
